# name: Build and Deploy Blog API UI

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: Build and Deploy to S3 Bucket
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20'

#       - name: Install dependencies
#         run: npm install

#       - name: Build Angular app
#         run: npm run build:blog-api-ui

#       - name: Deploy to S3
#         uses: jakejarvis/s3-sync-action@v0.5.1
#         with:
#           args: --acl public-read --follow-symlinks
#         env:
#           AWS_S3_BUCKET: api-ui.devluk.io
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: eu-north-1
#           SOURCE_DIR: 'dist/apps/blog-api-ui/browser'
