name: Build and Deploy Blog API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build:blog-api

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          APPLICATION_NAME: ${{ secrets.APPLICATION_BLOG_API_NAME }}
          ENVIRONMENT_NAME: ${{ secrets.APPLICATION_BLOG_API_ENVIRONMENT_NAME }}
          REGION: ${{ secrets.AWS_REGION }}
        run: |
          zip -r deploy.zip *
          aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $GITHUB_SHA --source-bundle S3Bucket=$APPLICATION_NAME,S3Key=$GITHUB_SHA.zip --region $REGION
          aws elasticbeanstalk update-environment --application-name $APPLICATION_NAME --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_SHA
